server:
  #定义端口
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    #${database.env:dev} 没有参数（如java -jar -Ddatabse.env=prod）时默认访问dev
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  #  #数据库配置
  #  datasource:
  #    username: root
  #    password: root
  #    url: jdbc:mysql://127.0.0.1:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    #数据库连接池
  #    hikari:
  #      connection-test-query: select 1
  #      connection-timeout: 20000
  #      idle-timeout: 300000
  #      maximum-pool-size: 5
  #      minimum-idle: 5
  #配置Redis参数
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  #   password: 123456
  #  #thymeleaf配置
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .html
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
#链接相关配置
short-link:
  #配置默认域名
  domain:
    defaull: localhost:8001
  #高德地图ip服务密钥
  stats:
    locale:
      amap-key: 8593e7a96162641f142f53a419991cb4
  goto-domain:
    white-list:
      enable: true
      names: 'b站,掘金,博客园等'
      details:
        - baidu.com
        - bilibili.com
        - juejin.cn
        - cnblogs.com
#消息队列配置
rocketmq:
  name-server: 127.0.0.1:9876
  #生产者
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    #全局超时时间
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  #消费者
  consumer:
    group: short-link_project-service_stats-save_cg
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/project/shortlink/project/dao/mapper/xml/*.xml #扫描xml