server:
  #定义端口
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
#  #数据库配置
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/shortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #数据库连接池
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  #配置Redis参数
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456

##mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/project/shortlink/admin/dao/mapper/xml/*.xml #扫描xml